/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownLoadInfo: typeof import('./src/components/DownLoadInfo/index.vue')['default']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
  }
}
